#:schema node_modules/wrangler/config-schema.json
name = "sublink-gcr"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "57d38109aada4b3cb9943c9e651b311b" }
]

[assets]
directory = "./public"
